appname: testGolang

server :
    address : localhost:8080

db:
    address:     localhost
    user:        dumyuser
    dbname :     orders
    password:   dumypassword
    port:       3306

logpath: /tmp/log

apikey: AIzaSyBzuM7atg360ClN4hmao7J3Y0UbvxSrkx8
